Added option for outputting an IDE specific formatting file
- currently only supports sublime
- emacs and vim to come

diff --git a/spruce b/spruce
--- a/spruce
+++ b/spruce
@@ -16,16 +16,21 @@ Spruce: Don't Let Messes Overstay Their Welcome
 Handy-dandy oblong-specific C++ code beautifier
 See https://gitlab.oblong.com/platform/docs/wikis/coding-style/
 
-usage: spruce [-o outdir] file...     (reformat given files)
-or:    spruce [-o outdir] all         (reformat all files)
-or:    spruce changes                 (reformat all edits, staged and unstaged)
-or:    spruce check [files...]        (list files that need reformatting)
-or:    spruce precommit               (abort if a staged file needs reformatting)
+usage: spruce [-o outdir] file...         (reformat given files)
+or:    spruce [-o outdir] all             (reformat all files)
+or:    spruce changes                     (reformat all edits, staged and unstaged)
+or:    spruce check [files...]            (list files that need reformatting)
+or:    spruce precommit                   (abort if a staged file needs reformatting)
 or:    spruce freebase <sha1_before_reformat> <sha1_after_reformat> <upstream_branch>
-or:    spruce style                   (output our .clang-format to stdout)
+or:    spruce plugin (emacs|vim|sublime)  (custom plugin support)
+or:    spruce style                       (output our .clang-format to stdout)
 
 'freebase' is for fixing a branch that is stale because upstream was spruced up
 after the branch was created.
+
+'plugin' has options for emacs, vim or sublime:
+    'sublime': produces a file, 'clang_format_custom.sublime-settings' which
+               should be used with the plugin: https://packagecontrol.io/packages/Clang%20Format
 _EOF_
   if $IN_ERR
   then
@@ -533,6 +538,69 @@ format_changes() {
   done
 }
 
+sublime_wants_containers_on_single_line() {
+  perl -e 'while (<STDIN>) {
+            if (/:( +)"[[{]/) { $merge=1; };
+            if ($merge) {
+              s/"(\w+)"/'\''$1'\''/g;
+              s/\n$//;
+              if (/[]}]/) { $merge=0;  s/$/\n/; };
+            };
+            print;
+          }'
+}
+
+reformat_sublime() {
+  echo "{"
+
+  # in the order of the lines below:
+  #   1. Put all keys/vals (words) in double quotes (i.e k: v -> "k": "v")
+  #   2. Put quotes around array blocks (i.e. [] -> "[]")
+  #   3. Add a comma at the end of every line
+  #   4/5. Put quotes around map blocks (i.e. {} -> "{}")
+  #   6. For every array/map block, remove new lines and replace double quotes with singles
+  #   7/8. Path fallout from #6 which changes the initial key to single quotes (bad)
+  #   9. Skip empty strings
+  perl -p \
+    -e 's/(([A-Za-z]+[0-9_-]*)+)/"$1"/g;' \
+    -e 's/(\[.*])/"$1"/g;' \
+    -e 's/\n/,\n/g;' \
+    -e 's/{/"{/g;' \
+    -e 's/}/}"/g;' \
+  | sublime_wants_containers_on_single_line \
+  | perl -p \
+      -e 's/'\''BraceWrapping'\''/"BraceWrapping"/g;' \
+      -e 's/'\''ForEachMacros'\''/"ForEachMacros"/g;' \
+  | grep -v "''" \
+  #
+
+  echo "}"
+}
+
+deploy_plugin() {
+  case "$1" in
+    emacs)
+      echo "ERROR: emacs not yet supported"
+      ;;
+    vim)
+      echo "ERROR: vim not yet supported"
+      ;;
+    sublime)
+      cat_style_file | reformat_sublime > clang_format_custom.sublime-settings
+      ;;
+    *)
+      cat <<_EOF_
+ERROR: plugin takes an argument to specify the IDE.
+Options are: 'emacs', 'vim', or 'sublime'
+You provided: '$1'
+
+_EOF_
+      print_help_menu
+      exit 1
+      ;;
+  esac
+}
+
 # Print pretty error message to stderr so it doesn't interfere with the list
 # of files, in case someone wants to redirect it to a file.
 print_error_header() {
@@ -585,6 +653,19 @@ check_files() {
 case "$1" in
   style)
     cat_style_file
+    ;;
+  plugin)
+    # Provide plugin support for given IDE
+    if [ $# -ne 2 ] ; then
+      cat <<_EOF_
+ERROR: plugin takes an argument to specify the IDE.
+Options are: 'emacs', 'vim', or 'sublime'
+
+_EOF_
+      IN_ERR=true
+      print_help_menu
+    fi
+    deploy_plugin $2
     ;;
   all)
     # format all .C/.c/.h/.cpp files that are not in the IGNORE_PATHS
